### ISSUE TITLE
iOS spotify

### ISSUE THREAD

**Issue by nguyenchr** [weswes/react-native-now-playing#1]
Was wondering if you knew if it was possible to use this on iOS for currently playing spotify song?
I did read somewhere that you might have to integrate with the spotify SDK, was wondering if you had tried this?

**Comment by weswes** [comment]
For iOS, the detection performed by this lib is only for the base music app.
I'm working on the integration of the Deezer SDK.
Spotify will come next, but it seems possible (and there is a RN module for spotify: https://github.com/viestat/react-native-spotify).

**Comment by nguyenchr** [comment]
@weswes thanks for the reply, yeah I started looking into the spotify sdk and it seems possible, just wanted to double check that this lib doesn't support it natively...thanks again
